package com.healthtech.patient

import android.os.Build
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyPermanentlyInvalidatedException
import android.security.keystore.KeyProperties
import android.security.keystore.StrongBoxUnavailableException
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * Hardware sealing of the patient master key (issue #11), envelope-encryption model
 * (ADR 0006).
 *
 * The master key itself is generated by the Rust crypto-core; it cannot *be* a
 * non-exportable Keystore key, so instead a non-exportable **KEK** (Key-Encryption-Key)
 * is generated *by* the Android Keystore — StrongBox (secure element) when present, TEE
 * fallback otherwise — and used to AES-GCM-wrap the master key. Only the wrapped blob is
 * ever persisted; the clear master key never touches disk.
 *
 * No software fallback (G3): if no hardware-backed keystore is available the operation
 * fails with [KeystoreError.UNAVAILABLE] rather than sealing under a software key.
 *
 * Nothing here logs key, blob, or PII material (G5).
 */
class KeystoreSealer {

    /** Typed failure reasons mapped 1:1 to the Dart [KeystoreException] hierarchy. */
    enum class KeystoreError(val code: String) {
        UNAVAILABLE("KEYSTORE_UNAVAILABLE"),
        STRONGBOX_UNSUPPORTED("STRONGBOX_UNSUPPORTED"),
        KEY_INVALIDATED("KEY_INVALIDATED"),
    }

    /** Carries a typed error code across the platform channel. */
    class SealerException(val error: KeystoreError, message: String) : Exception(message)

    /**
     * Seal [clearKey] (the raw 32-byte master key from Rust) under the hardware KEK.
     * Returns `version || iv || ciphertext+tag`.
     */
    fun seal(clearKey: ByteArray): ByteArray {
        val kek = getOrCreateKek()
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, kek)
        val iv = cipher.iv // 12 bytes for GCM
        val sealed = cipher.doFinal(clearKey) // ciphertext || 16-byte tag

        return ByteArray(1 + iv.size + sealed.size).also {
            it[0] = BLOB_VERSION
            System.arraycopy(iv, 0, it, 1, iv.size)
            System.arraycopy(sealed, 0, it, 1 + iv.size, sealed.size)
        }
    }

    /** Unseal a blob produced by [seal] back to the clear master key (in-memory only). */
    fun unseal(blob: ByteArray): ByteArray {
        if (blob.isEmpty() || blob[0] != BLOB_VERSION || blob.size < 1 + GCM_IV_LEN + GCM_TAG_LEN) {
            throw SealerException(KeystoreError.UNAVAILABLE, "malformed sealed blob")
        }
        val kek = loadKek()
            ?: throw SealerException(KeystoreError.UNAVAILABLE, "no hardware key present")

        val iv = blob.copyOfRange(1, 1 + GCM_IV_LEN)
        val ciphertext = blob.copyOfRange(1 + GCM_IV_LEN, blob.size)
        val cipher = Cipher.getInstance(TRANSFORMATION)
        try {
            cipher.init(Cipher.DECRYPT_MODE, kek, GCMParameterSpec(GCM_TAG_LEN * 8, iv))
            return cipher.doFinal(ciphertext)
        } catch (e: KeyPermanentlyInvalidatedException) {
            // OS update / biometric re-enroll / OEM TEE wipe -> route to recovery (#12).
            throw SealerException(KeystoreError.KEY_INVALIDATED, "hardware key invalidated")
        }
    }

    /** Whether the hardware KEK currently exists (idempotence / startup routing, G6). */
    fun exists(): Boolean = loadKek() != null

    /** Delete the hardware KEK (crypto-erase). */
    fun clear() {
        keystore().deleteEntry(KEK_ALIAS)
    }

    // --- internals ---------------------------------------------------------------

    private fun getOrCreateKek(): SecretKey = loadKek() ?: createKek()

    private fun loadKek(): SecretKey? {
        val entry = keystore().getEntry(KEK_ALIAS, null) as? KeyStore.SecretKeyEntry
        return entry?.secretKey
    }

    /**
     * Create the non-exportable KEK: AES-256-GCM, StrongBox when supported, TEE fallback,
     * and a hard failure if the result is not hardware-backed (G3).
     */
    private fun createKek(): SecretKey {
        val generator = KeyGenerator.getInstance(
            KeyProperties.KEY_ALGORITHM_AES,
            ANDROID_KEYSTORE,
        )

        fun spec(strongBox: Boolean): KeyGenParameterSpec {
            val builder = KeyGenParameterSpec.Builder(
                KEK_ALIAS,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
            )
                .setKeySize(256)
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                // setUserAuthenticationRequired is left off for offline onboarding UX
                // (#13/#28 will arbitrate enabling it). The key is still non-exportable.
            if (strongBox && Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
                builder.setIsStrongBoxBacked(true)
            }
            return builder.build()
        }

        // Prefer StrongBox (secure element); fall back to TEE if unavailable.
        val key = try {
            generator.init(spec(strongBox = true))
            generator.generateKey()
        } catch (e: StrongBoxUnavailableException) {
            generator.init(spec(strongBox = false))
            generator.generateKey()
        }

        // Refuse a software-only key: hardware sealing is the whole point (G3).
        if (!isHardwareBacked(key)) {
            clear()
            throw SealerException(
                KeystoreError.UNAVAILABLE,
                "no hardware-backed keystore (StrongBox/TEE) available",
            )
        }
        return key
    }

    private fun isHardwareBacked(key: SecretKey): Boolean {
        return try {
            val factory = javax.crypto.SecretKeyFactory.getInstance(key.algorithm, ANDROID_KEYSTORE)
            val info = factory.getKeySpec(key, android.security.keystore.KeyInfo::class.java)
                as android.security.keystore.KeyInfo
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
                info.securityLevel != android.security.keystore.KeyProperties.SECURITY_LEVEL_SOFTWARE
            } else {
                @Suppress("DEPRECATION")
                info.isInsideSecureHardware
            }
        } catch (e: Exception) {
            // If we cannot prove hardware backing, treat it as unavailable (fail closed).
            false
        }
    }

    private fun keystore(): KeyStore =
        KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }

    companion object {
        private const val ANDROID_KEYSTORE = "AndroidKeyStore"
        // Versioned alias so a future KEK rotation / algo change is additive.
        private const val KEK_ALIAS = "healthtech.master.kek.v1"
        private const val TRANSFORMATION = "AES/GCM/NoPadding"
        private const val GCM_IV_LEN = 12
        private const val GCM_TAG_LEN = 16
        private const val BLOB_VERSION: Byte = 1
    }
}
