// Android Keystore (StrongBox/TEE) platform-channel shim — Dart side (issue #11).
//
// ADR 0001 + ADR 0006: the patient master key is generated inside the Rust
// crypto-core, then SEALED in the Android Keystore. Flutter plugins do not
// expose `setIsStrongBoxBacked` / TEE fallback, so this MANDATORY, security-
// critical Kotlin MethodChannel shim does the sealing. The native side lives in
// android/app/src/main/kotlin/.../KeystoreSealer.kt (iOS amorce in
// ios/Runner/KeystoreChannelPlugin.swift).
//
// Trust model (envelope encryption, ADR 0006):
//   - The native side owns a NON-EXPORTABLE hardware KEK (Key-Encryption-Key),
//     generated by the Keystore with StrongBox when present, TEE fallback
//     otherwise. The KEK never leaves hardware.
//   - `seal(clearKey)` returns the master key wrapped (AES-GCM) by that KEK.
//     Only the sealed blob is ever persisted; the clear key is never on disk.
//   - `unseal(blob)` returns the clear key in memory only, handed straight back
//     to the Rust core, used, then wiped.
//
// There is NO software fallback: if no hardware keystore is available the native
// side fails loudly and this shim maps that to a typed exception (G3). A silent
// software key would break the zero-knowledge / "phone theft" guarantee.
//
// `flutter_secure_storage` is used ONLY for non-critical items, never for the
// master key or the sealed-blob persistence path (ADR 0001).

import 'package:flutter/services.dart';

/// Base type for all keystore-shim failures surfaced to app code.
sealed class KeystoreException implements Exception {
  const KeystoreException(this.message);

  /// Human-readable, non-secret detail (never contains key/blob material).
  final String message;

  @override
  String toString() => '$runtimeType: $message';
}

/// No hardware-backed keystore is available (neither StrongBox nor TEE), or the
/// keystore operation failed for an unrecoverable reason. We do NOT degrade to a
/// software key (G3) — the caller must surface this rather than proceed.
class KeystoreUnavailable extends KeystoreException {
  const KeystoreUnavailable(super.message);
}

/// The device lacks StrongBox specifically. The native side falls back to a
/// TEE-backed key on its own; this is only thrown if the native side reports
/// StrongBox as a hard requirement that could not be met.
class StrongBoxUnsupported extends KeystoreException {
  const StrongBoxUnsupported(super.message);
}

/// The hardware key was permanently invalidated (OS update, biometric re-enroll,
/// OEM TEE wipe). The sealed blob can no longer be unsealed — route the user to
/// the PBKDF2 recovery flow (#12) rather than crashing or losing data silently.
class KeyInvalidated extends KeystoreException {
  const KeyInvalidated(super.message);
}

/// Dart handle to the native key-sealing shim.
///
/// Routes every operation through the `healthtech/keystore` [MethodChannel];
/// it must NEVER silently degrade to a software key. Native error codes are
/// mapped to the typed [KeystoreException]s above.
class KeystoreChannel {
  /// Inject a channel in tests (mocked); defaults to the production channel.
  const KeystoreChannel([
    MethodChannel channel = const MethodChannel('healthtech/keystore'),
  ]) : _channel = channel;

  final MethodChannel _channel;

  // Native error codes (mirrored in the Kotlin/Swift shim).
  static const String _codeUnavailable = 'KEYSTORE_UNAVAILABLE';
  static const String _codeStrongBoxUnsupported = 'STRONGBOX_UNSUPPORTED';
  static const String _codeKeyInvalidated = 'KEY_INVALIDATED';

  /// Seal the Rust-produced clear master key in hardware (StrongBox/TEE) and
  /// return the sealed blob (`version || iv || ciphertext || tag`).
  ///
  /// [clearKey] are the raw 32 bytes from `CryptoCore.exportSealable`; the native
  /// side wraps them with the hardware KEK. Only the returned blob may be
  /// persisted — never [clearKey]. The caller must wipe [clearKey] immediately.
  Future<Uint8List> seal(Uint8List clearKey) async {
    final blob = await _invoke<Uint8List>('seal', {'clearKey': clearKey});
    if (blob == null) {
      throw const KeystoreUnavailable('seal returned no sealed blob');
    }
    return blob;
  }

  /// Unseal a previously sealed blob back to the clear master key, in memory only.
  ///
  /// The result must be handed straight to the Rust core and wiped after use; it
  /// is never written to disk or logged.
  Future<Uint8List> unseal(Uint8List sealedBlob) async {
    final clear = await _invoke<Uint8List>('unseal', {'sealedBlob': sealedBlob});
    if (clear == null) {
      throw const KeystoreUnavailable('unseal returned no key material');
    }
    return clear;
  }

  /// Whether a hardware KEK already exists for this device/install (idempotence,
  /// G6): used at startup to decide onboarding (#13) vs. normal open.
  Future<bool> exists() async {
    final present = await _invoke<bool>('exists', const {});
    return present ?? false;
  }

  /// Delete the hardware KEK. After this the sealed blob is unrecoverable
  /// (crypto-erase). Callers are responsible for also removing the sealed blob.
  Future<void> clear() => _invoke<void>('clear', const {});

  /// Backwards-compatible alias kept for the earlier stub name; prefer [seal].
  @Deprecated('Use seal(clearKey); the parameter is the raw key, native seals it')
  Future<Uint8List> sealMasterKey(Uint8List clearKey) => seal(clearKey);

  Future<T?> _invoke<T>(String method, Map<String, Object?> args) async {
    try {
      return await _channel.invokeMethod<T>(method, args);
    } on PlatformException catch (e) {
      switch (e.code) {
        case _codeKeyInvalidated:
          throw KeyInvalidated(e.message ?? 'hardware key invalidated');
        case _codeStrongBoxUnsupported:
          throw StrongBoxUnsupported(e.message ?? 'StrongBox unavailable');
        case _codeUnavailable:
          throw KeystoreUnavailable(e.message ?? 'hardware keystore unavailable');
        default:
          // Unknown native failure: fail closed as unavailable — never fall back.
          throw KeystoreUnavailable('keystore error (${e.code})');
      }
    } on MissingPluginException {
      // The native shim is not registered (e.g. unsupported platform / host test):
      // fail loudly rather than degrade to software crypto (G3).
      throw const KeystoreUnavailable('keystore platform shim not available');
    }
  }
}
