// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Seal [master_key_clear] under a PBKDF2-derived recovery key (#12, G2).
///
/// [master_key_clear] must be exactly [KEY_LEN] bytes (the clear master key).
/// [secret] is the passphrase or output of [normalize_answers].
/// [iterations] is clamped to the minimum floor internally.
/// Returns the self-describing envelope bytes.
Future<Uint8List> sealRecovery(
        {required List<int> masterKeyClear,
        required List<int> secret,
        required int iterations}) =>
    RustLib.instance.api.crateApiSealRecovery(
        masterKeyClear: masterKeyClear, secret: secret, iterations: iterations);

/// Open a recovery envelope and return the master key handle (#12, G1).
///
/// Throws on wrong secret, corrupted envelope, or unknown version/KDF
/// — coarse error, no oracle (THR-05).
Future<CryptoHandle> openRecovery(
        {required List<int> secret, required List<int> envelope}) =>
    RustLib.instance.api
        .crateApiOpenRecovery(secret: secret, envelope: envelope);

/// Normalize and concatenate security-question answers for PBKDF2 (G6).
///
/// Delegates to the Rust normalize_recovery_answers function: lowercase,
/// diacritic-fold, drop punctuation, join with Unit Separator. Deterministic.
Future<Uint8List> normalizeAnswers({required List<String> answers}) =>
    RustLib.instance.api.crateApiNormalizeAnswers(answers: answers);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CryptoHandle>>
abstract class CryptoHandle implements RustOpaqueInterface {
  /// Decrypt a blob produced by [encrypt_record].
  ///
  /// Returns Err on a bad key, wrong tag, or corrupted blob — coarse, no oracle.
  Future<Uint8List> decryptRecord({required List<int> blob});

  /// Encrypt [plaintext] with AES-256-GCM. Returns `nonce(12) || ct || tag(16)`.
  Future<Uint8List> encryptRecord({required List<int> plaintext});

  /// Export the clear key bytes for immediate hardware sealing (G8).
  ///
  /// This is the one sanctioned point where the clear key crosses the FFI.
  /// The caller must pass the result straight to the Keystore shim and never
  /// persist, log, or transmit it.
  Future<Uint8List> exportSealable();

  /// Re-wrap hardware-unsealed clear bytes back into a handle.
  ///
  /// Returns Err if `bytes` is not exactly [KEY_LEN] bytes.
  /// The caller must wipe `bytes` after this call.
  static Future<CryptoHandle> fromClearBytes({required List<int> bytes}) =>
      RustLib.instance.api.crateApiCryptoHandleFromClearBytes(bytes: bytes);

  /// Generate a fresh 256-bit master key from the OS CSPRNG.
  ///
  /// Panics only if the OS has no entropy source (unrecoverable).
  static Future<CryptoHandle> generate() =>
      RustLib.instance.api.crateApiCryptoHandleGenerate();

  /// Zeroize the master key inside this handle (G5). Consumes the handle.
  ///
  /// Drop already calls Zeroizing's destructor; this consuming method makes the
  /// "use then wipe" contract explicit at every call site.
  Future<void> wipe();
}
