// flutter_rust_bridge facade for crypto-core (ADR 0001 / ADR 0003).
//
// The REAL bindings under lib/src/rust/** are GENERATED by the
// flutter_rust_bridge (FRB) codegen run against the `crypto-core` crate; they
// are excluded from analysis (see analysis_options.yaml) and are produced once
// a Flutter SDK + the FRB toolchain are available. They are NOT committed here.
//
// This file defines the *stable, hand-written seam* the rest of the app codes
// against (`CryptoCore`, `MasterKeyHandle`), plus the FRB-backed implementation
// (`FrbCryptoCore`) that delegates to the generated bindings. Coding against the
// interface keeps the master-key flow (see master_key_service.dart) unit-testable
// with a fake core while the native lib is unavailable in this environment.
//
// The FFI surface is intentionally tiny (ADR 0003): clients call only the
// audited high-level functions. NO cipher logic ever lives in Dart, and the
// clear key never crosses this boundary except through `exportSealable`, whose
// only caller is the immediate hardware-sealing step (issue #11, G8).
//
// The Rust API + wire format are FROZEN by #10 — codegen must mirror it exactly,
// never reinterpret it: encryptRecord returns `nonce(12) || ciphertext || tag(16)`
// (28-byte overhead), and decryptRecord surfaces a single coarse error (no oracle)
// and never returns plaintext on a bad key/tag/blob. See crypto-core/README.md and
// docs/security/crypto-core-review.md.

import 'dart:typed_data';

/// Opaque Dart-side reference to a master key that lives **inside the Rust core**.
///
/// Dart never holds the clear key behind this handle; it only passes the handle
/// back across the FFI for [CryptoCore.exportSealable] (sealing) and
/// [CryptoCore.wipe] (zeroize). With real FRB codegen this is replaced by the
/// generated opaque type; the interface below is what app code depends on.
abstract class MasterKeyHandle {}

/// The single cryptography entry point for the patient app (ADR 0003).
///
/// Mirrors the Rust `crypto-core` master-key surface (issue #11). Implementations
/// must never fall back to Dart-side crypto.
abstract class CryptoCore {
  /// Generate a fresh 256-bit master key inside the Rust core (OS CSPRNG).
  ///
  /// The clear key stays in Rust; only an opaque [MasterKeyHandle] is returned.
  Future<MasterKeyHandle> generateMasterKey();

  /// Export the clear key bytes **for immediate hardware sealing only** (G8).
  ///
  /// This is the one sanctioned point where the clear key crosses the FFI. The
  /// caller must pass the result straight to the Keystore shim and never persist,
  /// log, or transmit it.
  Future<Uint8List> exportSealable(MasterKeyHandle handle);

  /// Re-wrap clear bytes that hardware has just unsealed back into a handle (#14).
  Future<MasterKeyHandle> handleFromUnsealed(Uint8List clearBytes);

  /// Zeroize the clear key behind [handle] inside the Rust core (G5).
  Future<void> wipe(MasterKeyHandle handle);
}

/// Raised when the generated FRB bindings (and the native `crypto-core` library)
/// are not available — e.g. before codegen has run or in a host-only test env.
///
/// Failing loudly here is deliberate: there is NO Dart-side crypto fallback
/// (forbidden by ADR 0001 / ADR 0003).
class CryptoCoreUnavailable implements Exception {
  const CryptoCoreUnavailable();

  @override
  String toString() =>
      'crypto-core FRB bindings not generated yet — run the flutter_rust_bridge '
      'codegen against crypto-core (see app-patient/README.md, TODO(#11)).';
}

/// [CryptoCore] backed by the generated `flutter_rust_bridge` bindings.
///
/// TODO(#11): once codegen has run, delegate each method to the generated
/// `RustLib` API (e.g. `RustLib.instance.api.cryptoCoreMasterKeyHandleGenerate()`).
/// Until then every method throws [CryptoCoreUnavailable] so callers fail loudly
/// instead of silently degrading to insecure Dart crypto.
class FrbCryptoCore implements CryptoCore {
  const FrbCryptoCore();

  @override
  Future<MasterKeyHandle> generateMasterKey() async =>
      throw const CryptoCoreUnavailable();

  @override
  Future<Uint8List> exportSealable(MasterKeyHandle handle) async =>
      throw const CryptoCoreUnavailable();

  @override
  Future<MasterKeyHandle> handleFromUnsealed(Uint8List clearBytes) async =>
      throw const CryptoCoreUnavailable();

  @override
  Future<void> wipe(MasterKeyHandle handle) async =>
      throw const CryptoCoreUnavailable();
}
